In [2]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv(r"C:\Users\vansh\Downloads\archive (2)\housing.csv")
#It reads the data and allocates memory

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [9]:
#to get total no of rows and colunms
df.shape

(20640, 10)

In [11]:
#to get columns names
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [12]:
df.info() # it gives the datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [13]:
#to get first 10 records
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY

In [14]:
#to get last 10 records
df.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20630,-121.32,39.29,11.0,2640.0,505.0,1257.0,445.0,3.5673,112000.0,INLAND
20631,-121.40,39.33,15.0,2655.0,493.0,1200.0,432.0,3.5179,107200.0,INLAND
20632,-121.45,39.26,15.0,2319.0,416.0,1047.0,385.0,3.1250,115600.0,INLAND
20633,-121.53,39.19,27.0,2080.0,412.0,1082.0,382.0,2.5495,98300.0,INLAND
20634,-121.56,39.27,28.0,2332.0,395.0,1041.0,344.0,3.7125,116800.0,INLAND
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [15]:
df.describe()   # for numeric columns

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [16]:
df.describe(include='object')   # for categorical columns

       ocean_proximity
count            20640
unique               5
top          <1H OCEAN
freq              9136

In [18]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [19]:
df.duplicated().sum()

0

In [25]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [21]:
df.corr(numeric_only=True)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,1.000000,-0.924664,-0.108197,0.044568,0.069608,0.099773,0.055310,-0.015176,-0.045967
latitude,-0.924664,1.000000,0.011173,-0.036100,-0.066983,-0.108785,-0.071035,-0.079809,-0.144160
housing_median_age,-0.108197,0.011173,1.000000,-0.361262,-0.320451,-0.296244,-0.302916,-0.119034,0.105623
total_rooms,0.044568,-0.036100,-0.361262,1.000000,0.930380,0.857126,0.918484,0.198050,0.134153
total_bedrooms,0.069608,-0.066983,-0.320451,0.930380,1.000000,0.877747,0.979728,-0.007723,0.049686
population,0.099773,-0.108785,-0.296244,0.857126,0.877747,1.000000,0.907222,0.004834,-0.024650
households,0.055310,-0.071035,-0.302916,0.918484,0.979728,0.907222,1.000000,0.013033,0.065843
median_income,-0.015176,-0.079809,-0.119034,0.198050,-0.007723,0.004834,0.013033,1.000000,0.688075
median_house_value,-0.045967,-0.144160,0.105623,0.134153,0.049686,-0.024650,0.065843,0.688075,1.000000

In [36]:
import pandas as pd

# Load dataset
df1 = pd.read_csv(r"C:\Users\vansh\Downloads\archive (3)\world_real_estate_data(147k).csv")

# Shape
df1.shape

(147536, 14)

In [37]:
df1.columns

Index(['title', 'country', 'location', 'building_construction_year',
       'building_total_floors', 'apartment_floor', 'apartment_rooms',
       'apartment_bedrooms', 'apartment_bathrooms', 'apartment_total_area',
       'apartment_living_area', 'price_in_USD', 'image', 'url'],
      dtype='object')

In [40]:
df1.head(5)

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...

In [41]:
df1.tail(5)

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147536 entries, 0 to 147535
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       147536 non-null  object
 1   country                     147406 non-null  object
 2   location                    147405 non-null  object
 3   building_construction_year  64719 non-null   float64
 4   building_total_floors       68224 non-null   float64
 5   apartment_floor             54592 non-null   float64
 6   apartment_rooms             74178 non-null   float64
 7   apartment_bedrooms          36982 non-null   float64
 8   apartment_bathrooms         55973 non-null   float64
 9   apartment_total_area        141796 non-null  object
 10  apartment_living_area       27712 non-null   object
 11  price_in_USD                144961 non-null  float64
 12  image                       147536 non-null  object
 13  url                         147536 non-null  object
dtypes: float64(7), object(7)
memory usage: 15.8+ MB

In [44]:
df1.describe()

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,price_in_USD
count,64719.000000,68224.000000,54592.000000,74178.000000,36982.000000,55973.000000,1.449610e+05
mean,1996.921754,8.575692,5.791709,2.572097,2.289222,1.364229,4.121722e+05
std,157.527635,8.356781,5.541368,1.319545,18.276913,0.745019,8.420984e+05
min,1.000000,-1.000000,-2.000000,-1.000000,-1.000000,1.000000,0.000000e+00
25%,2004.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.054200e+05
50%,2021.000000,5.000000,4.000000,2.000000,2.000000,1.000000,1.902120e+05
75%,2024.000000,14.000000,8.000000,3.000000,3.000000,2.000000,3.989300e+05
max,2316.000000,124.000000,202.000000,124.000000,2009.000000,43.000000,3.060283e+07

In [45]:
df1.isnull()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,False,False,False,True,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,True,True,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,False,False,False,True,True,True,True,False,True,False,True,False,False,False
147532,False,False,False,False,False,True,False,False,False,False,False,False,False,False
147533,False,False,False,True,True,True,False,False,False,True,False,False,False,False
147534,False,False,False,False,True,True,True,True,True,True,True,False,False,False
147535,False,False,False,True,False,True,False,False,True,False,True,False,False,False

In [46]:
df1.isnull().sum()

title                              0
country                          130
location                         131
building_construction_year     82817
building_total_floors          79312
apartment_floor                92944
apartment_rooms                73358
apartment_bedrooms            110554
apartment_bathrooms            91563
apartment_total_area            5740
apartment_living_area         119824
price_in_USD                    2575
image                              0
url                                0
dtype: int64

In [47]:
df1.duplicated().sum()

0

In [48]:
df1.nunique()

title                          78292
country                           27
location                        7445
building_construction_year       224
building_total_floors             86
apartment_floor                   70
apartment_rooms                   34
apartment_bedrooms                31
apartment_bathrooms               19
apartment_total_area            1492
apartment_living_area            641
price_in_USD                   49327
image                         113753
url                           147536
dtype: int64

In [49]:
df.corr(numeric_only=True)

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,price_in_USD
building_construction_year,1.000000,0.096658,0.085043,-0.053854,-0.041845,-0.022095,0.000617
building_total_floors,0.096658,1.000000,0.709739,-0.125420,-0.094493,-0.030828,-0.024754
apartment_floor,0.085043,0.709739,1.000000,-0.105771,-0.045982,-0.026766,-0.009395
apartment_rooms,-0.053854,-0.125420,-0.105771,1.000000,0.720481,0.452677,0.279506
apartment_bedrooms,-0.041845,-0.094493,-0.045982,0.720481,1.000000,0.048195,0.017441
apartment_bathrooms,-0.022095,-0.030828,-0.026766,0.452677,0.048195,1.000000,0.419841
price_in_USD,0.000617,-0.024754,-0.009395,0.279506,0.017441,0.419841,1.000000

In [50]:
import pandas as pd

# Load dataset
sm = pd.read_csv(r"C:\Users\vansh\Downloads\archive (4)\Real Estate Data V21.csv")

# Shape
sm.shape

(14528, 9)

In [51]:
sm.columns

Index(['Name', 'Property Title', 'Price', 'Location', 'Total_Area',
       'Price_per_SQFT', 'Description', 'Baths', 'Balcony'],
      dtype='object')

In [52]:
sm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14528 entries, 0 to 14527
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            14528 non-null  object
 1   Property Title  14528 non-null  object
 2   Price           14528 non-null  object
 3   Location        14528 non-null  object
 4   Total_Area      14528 non-null  int64
 5   Price_per_SQFT  14528 non-null  float64
 6   Description     14528 non-null  object
 7   Baths           14528 non-null  int64
 8   Balcony         14528 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 1021.6+ KB

In [53]:
sm.describe()

         Total_Area  Price_per_SQFT         Baths
count  14528.000000    14528.000000  14528.000000
mean    1297.916988    11719.456222      2.751239
std     1245.694305    49036.068632      0.898243
min       70.000000        0.000000      1.000000
25%      650.000000     4480.000000      2.000000
50%     1000.000000     6050.000000      3.000000
75%     1439.000000     9312.500000      3.000000
max    35000.000000   999000.000000      6.000000

In [54]:
sm.head(5)

,Name,Property Title,Price,Location,Total_Area,Price_per_SQFT,Description,Baths,Balcony
0,Casagrand ECR 14,"4 BHK Flat for sale in Kanathur Reddikuppam, C...",₹1.99 Cr,"Kanathur Reddikuppam, Chennai",2583,7700.0,Best 4 BHK Apartment for modern-day lifestyle ...,4,Yes
1,"Ramanathan Nagar, Pozhichalur,Chennai",10 BHK Independent House for sale in Pozhichal...,₹2.25 Cr,"Ramanathan Nagar, Pozhichalur,Chennai",7000,3210.0,Looking for a 10 BHK Independent House for sal...,6,Yes
2,DAC Prapthi,"3 BHK Flat for sale in West Tambaram, Chennai",₹1.0 Cr,"Kasthuribai Nagar, West Tambaram,Chennai",1320,7580.0,"Property for sale in Tambaram, Chennai. This 3...",3,No
3,"Naveenilaya,Chepauk, Triplicane,Chennai",7 BHK Independent House for sale in Triplicane...,₹3.33 Cr,"Naveenilaya,Chepauk, Triplicane,Chennai",4250,7840.0,Entire Building for sale with 7 units of singl...,5,Yes
4,VGN Spring Field Phase 1,"2 BHK Flat for sale in Avadi, Chennai",₹48.0 L,"Avadi, Chennai",960,5000.0,"Property for sale in Avadi, Chennai. This 2 BH...",3,Yes

In [55]:
sm.tail(5)

,Name,Property Title,Price,Location,Total_Area,Price_per_SQFT,Description,Baths,Balcony
14523,"Krishna Park Extension, Tilak Nagar,New Delhi","2 BHK Flat for sale in Tilak Nagar, New Delhi",₹40.0 L,"Krishna Park Extension, Tilak Nagar,New Delhi",1053,3800.0,Looking for a good 2 BHK Apartment in Tilak Na...,3,Yes
14524,"Rawta, Jaffarpur Kalan,New Delhi",1 BHK Independent House for sale in Jaffarpur ...,₹14.0 L,"Rawta, Jaffarpur Kalan,New Delhi",472,2970.0,1 BHK Independent House for sale in Jaffarpur ...,2,Yes
14525,"Rani Garden, Geeta Colony,New Delhi","1 BHK Flat for sale in Geeta Colony, New Delhi",₹30.0 L,"Rani Garden, Geeta Colony,New Delhi",378,7940.0,"Property for sale in Geeta Colony, Delhi. This...",1,Yes
14526,"Lig flat rohini,Sector 16E, Sector 16 Rohini,N...","3 BHK Flat for sale in Sector 16 Rohini, New D...",₹60.0 L,"Lig flat rohini,Sector 16E, Sector 16 Rohini,N...",700,8570.0,Check out this 3 BHK Apartment for sale in Roh...,2,Yes
14527,"Sector 3B, Sector 3 Rohini,New Delhi",1 RK Independent House for sale in Sector 3 Ro...,₹55.0 L,"Sector 3B, Sector 3 Rohini,New Delhi",344,15990.0,This is an independent DDA house(in raw condit...,1,Yes

In [56]:
sm.isnull().sum()

Name              0
Property Title    0
Price             0
Location          0
Total_Area        0
Price_per_SQFT    0
Description       0
Baths             0
Balcony           0
dtype: int64

In [58]:
sm.duplicated().sum()

8

In [61]:
sm.nunique()

Name               9998
Property Title     6507
Price               891
Location           7050
Total_Area         1774
Price_per_SQFT     2094
Description       14490
Baths                 6
Balcony               2
dtype: int64

In [62]:
sm.corr(numeric_only=True)

                Total_Area  Price_per_SQFT     Baths
Total_Area        1.000000        0.153151  0.529589
Price_per_SQFT    0.153151        1.000000  0.005869
Baths             0.529589        0.005869  1.000000

In [63]:
import pandas as pd

# Load dataset
sm = pd.read_csv(r"C:\Users\vansh\Downloads\archive (5)\real_estate_dataset.csv")

# Shape
sm.shape

(287, 9)

In [65]:
sm.columns

Index(['url', 'beds', 'city', 'date', 'size', 'type', 'baths', 'price',
       'neighborhood'],
      dtype='object')

In [66]:
sm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287 entries, 0 to 286
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   url           287 non-null    object
 1   beds          287 non-null    int64
 2   city          287 non-null    object
 3   date          287 non-null    object
 4   size          287 non-null    object
 5   type          287 non-null    object
 6   baths         287 non-null    int64
 7   price         287 non-null    float64
 8   neighborhood  287 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 20.3+ KB

In [67]:
sm.describe()

             beds       baths         price
count  287.000000  287.000000  2.870000e+02
mean     2.156794    1.526132  1.956434e+07
std      1.767959    1.771525  4.461799e+07
min      0.000000    0.000000  0.000000e+00
25%      0.000000    0.000000  4.738000e+06
50%      2.000000    1.000000  1.000000e+07
75%      3.000000    2.000000  2.085000e+07
max     12.000000   12.000000  6.000000e+08

In [68]:
sm.head(10)

,url,beds,city,date,size,type,baths,price,neighborhood
0,https://www.99acres.com/residential-land-plot-...,0,Bangalore,2025-02-19,799-1258 sqft,Residential land / Plot,0,2317000.0,Jigani
1,https://www.99acres.com/2-bhk-bedroom-apartmen...,2,Bangalore,2025-02-19,1085 sqft,2 BHK Flat,2,12500000.0,Tumkur Road
2,https://www.99acres.com/sumadhura-capitol-resi...,3,Bangalore,2025-02-19,1525-2150 sqft,"3, 4 BHK Apartment",0,23200000.0,Whitefield
3,https://www.99acres.com/provident-botanico-sou...,2,Bangalore,2025-02-19,658-1003 sqft,"2, 3 BHK Apartment",0,889000.0,Soukya Road
4,https://www.99acres.com/kvg-superior-kalkere-b...,2,Bangalore,2025-02-19,1179-1449 sqft,"2, 3 BHK Apartment",0,6483000.0,Kalkere
5,https://www.99acres.com/nambiar-district-25-sa...,2,Bangalore,2025-02-19,1199-2484 sqft,"2, 3, 4 BHK Apartment",0,15000000.0,Sarjapur Road
6,https://www.99acres.com/mahaveer-celesse-yelah...,2,Bangalore,2025-02-19,794-1923 sqft,"2, 3 BHK Apartment",0,7518000.0,Yelahanka
7,https://www.99acres.com/keya-life-by-the-lake-...,4,Bangalore,2025-02-19,0 sqft,"4, 5 BHK Villa",0,39800000.0,Hebbal
8,https://www.99acres.com/amrutha-platinum-tower...,2,Bangalore,2025-02-19,1006-1636 sqft,"2, 3 BHK Apartment",0,11100000.0,Whitefield
9,https://www.99acres.com/keya-spring-bannerghat...,2,Bangalore,2025-02-19,1335-2700 sqft,"2, 3, 4 BHK Apartment",0,15700000.0,Bannerghatta Road

In [69]:
sm.tail(5)

,url,beds,city,date,size,type,baths,price,neighborhood
282,https://www.99acres.com/3-bhk-bedroom-apartmen...,3,Pune,2025-01-19,840 sqft,Residential apartment,3,10000000.0,Manjari Khurd
283,https://www.99acres.com/2-bhk-bedroom-apartmen...,2,Pune,2025-02-13,690 sqft,Residential apartment,2,6500000.0,Punawale
284,https://www.99acres.com/6-bhk-bedroom-independ...,6,Pune,2025-01-19,840 sqft,Independent House/Villa,6,13500000.0,Katraj
285,https://www.99acres.com/1-bhk-bedroom-apartmen...,1,Pune,2025-02-17,640 sqft,Residential apartment,1,3500000.0,Kirkatwadi
286,https://www.99acres.com/3-bhk-bedroom-apartmen...,3,Pune,2025-02-12,878 sqft,Residential apartment,3,12000000.0,Mahalunge

In [70]:
sm.isnull()

       url   beds   city   date   size   type  baths  price  neighborhood
0    False  False  False  False  False  False  False  False         False
1    False  False  False  False  False  False  False  False         False
2    False  False  False  False  False  False  False  False         False
3    False  False  False  False  False  False  False  False         False
4    False  False  False  False  False  False  False  False         False
..     ...    ...    ...    ...    ...    ...    ...    ...           ...
282  False  False  False  False  False  False  False  False         False
283  False  False  False  False  False  False  False  False         False
284  False  False  False  False  False  False  False  False         False
285  False  False  False  False  False  False  False  False         False
286  False  False  False  False  False  False  False  False         False

[287 rows x 9 columns]

In [72]:
sm.isnull().sum()

url             0
beds            0
city            0
date            0
size            0
type            0
baths           0
price           0
neighborhood    0
dtype: int64

In [75]:
sm.duplicated().sum()

0

In [76]:
sm.nunique()

url             280
beds             11
city             26
date             25
size            211
type             48
baths            10
price           204
neighborhood    224
dtype: int64

In [3]:
import pandas as pd

# Load CSV
df = pd.read_csv(r"C:\Users\vansh\Downloads\archive (4)\Real Estate Data V21.csv")

In [ ]:
# we used re-regular expression (regex module) so that we can find the patterns such as 3bhk and 5 bhk so on..

In [4]:
import re

# we used astype to convert the column values into string and then from string values we converted it into lowercase
# and then stored it in separate column name called property_title.
df['property_title'] = df['Property Title'].astype(str).str.lower()

def extract_rooms(text):
    # it extracts the numbers like 3 and 4 and for identifying bhk we used *bhk
    match = re.search(r'(\d+(\.\d+)?)\s*bhk', text)
    if match:
        return float(match.group(1))

    # if there is any description like bedrooms we use below function
    match = re.search(r'(\d+)\s*bed(room)?', text)
    if match:
        return int(match.group(1))

    # if description is present such as rk using below function
    match = re.search(r'(\d+)\s*rk', text)
    if match:
        return int(match.group(1))

    return None

# stores no of rooms in new column called num_rooms
df['num_rooms'] = df['property_title'].apply(extract_rooms)
print(df[['property_title', 'num_rooms']].head(20))

                                       property_title  num_rooms
0   4 bhk flat for sale in kanathur reddikuppam, c...        4.0
1   10 bhk independent house for sale in pozhichal...       10.0
2       3 bhk flat for sale in west tambaram, chennai        3.0
3   7 bhk independent house for sale in triplicane...        7.0
4               2 bhk flat for sale in avadi, chennai        2.0
5            2 bhk flat for sale in siruseri, chennai        2.0
6           2 bhk flat for sale in sembakkam, chennai        2.0
7   3 bhk independent house for sale in mahindra w...        3.0
8       2 bhk flat for sale in west tambaram, chennai        2.0
9           1 bhk flat for sale in chromepet, chennai        1.0
10  1 bhk flat for sale in mahindra world city, ch...        1.0
11       3 bhk flat for sale in pallikaranai, chennai        3.0
12     6 bhk villa for sale in west mambalam, chennai        6.0
13        2 bhk flat for sale in ashok nagar, chennai        2.0
14        2 bhk flat for sale in madambakkam, chennai        2.0
15      3 bhk flat for sale in perungalathur, chennai        3.0
16           2 bhk flat for sale in padappai, chennai        2.0
17       3 bhk flat for sale in nungambakkam, chennai        3.0
18          4 bhk flat for sale in muttukadu, chennai        4.0
19  2 bhk independent house for sale in pozhichalu...        2.0